---

# Default values for master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  pullPolicy: Always
  tag: "8.0.29-debian"

service:
  name: "mysql-master"
  type: ClusterIP
  port: 3306

pod:
  port: 3306

resources:
  limits:
    cpu: 300m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

storageClassName: "mysql-master-sc"
storageCapacity: 5Gi

mysqlRootPassword: "root"
