---

# Default values for master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: Always
  tag: "14.3-alpine"

service:
  name: "postgres"
  type: ClusterIP
  port: 5432

pod:
  port: 5432

resources:
  limits:
    cpu: 300m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

storageClassName: "postgres-sc"
storageCapacity: 5Gi

postgresRootUser: "root"
postgresRootPassword: "root"
