---

# Default values for master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "redis"
  pullPolicy: Always
  tag: "7.0.1-alpine"

service:
  name: "redis"
  type: ClusterIP
  port: 6379

pod:
  port: 6379

resources:
  limits:
    cpu: 150m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
