---

name: YAML Lint
on: [push]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          strict: true
          warnings: true
          path: .
          config: ./yaml-lint-config.yaml